### ISSUE TITLE
example.py

### ISSUE THREAD

**Issue by wjohnston-sfdc** [spontit/bitbucket-webhook-string#1]
@joshwolff1  I am looking at your example.py and am confused as to why it is reading in the flat file (example.json). I thought the point of this was to parse the payload coming from bitbucket not reading in a local file.

Would you be able to update the example.py file to include how to print the payload to a file, or how to access one of the many event variables captured in the payload?

Cheers 👍

**Comment by joshwolff1** [comment]
"I thought the point of this was to parse the payload coming from bitbucket not reading in a local file."

That's correct. Example.json is the incoming payload. 

In order to access the event variables, that requires server-side code. You expose your server via an API to BitBucket, and then they send that json (as shown in example.json). So the code to do this is the exact same code as you would encounter when setting up a Flask API and reading a json payload (any json payload, not just BitBucket).

Because this is generally available online, I won't go into this in the example.py script, but I appreciate your interest in this repo.

Best of luck!
